@startuml
actor User
participant "Browser with app" as Browser #LightCyan

box "Dispatcher"
participant "Dispatcher" as Dispatcher
participant "Local Result cache" as LocalCache
end box

participant Storage


autonumber 10 10 "<b>[000]"


== Получение результа вычисления ==

Browser -> Dispatcher: GET запрос nрезультата вычисления \nзадачи по task_id 

Dispatcher -> Dispatcher: Валидация запроса
alt #Pink Запрос не валиден
  Dispatcher--> Browser: Code 400 Empty or missing task_id
  Browser--> User: Отображение статуса
  note over User:  Ситуация возможна при использовании консоли, curl и т.д. \nНеобходимо скорректировать параметры 
end

Dispatcher -> LocalCache: Поиск результата по task_id
LocalCache --> Dispatcher: Результат
alt #LightGreen  Найден(в кэше) результат для task_id
  Dispatcher--> Browser: Code 200 \n+ результат
  Browser--> User: Отображение статуса и результата
  note over User: Конец
end

Dispatcher -> Storage: Запрос результата по task_id  
Storage --> Dispatcher: Результат


alt #Pink Ошибка получения результата вычисления
  Dispatcher--> Browser: Code 500 Internal Server Error
  Browser--> User: Отображение статуса
  note over User: Пробует позже
end  

alt #Pink Запись с данным task_id не найдена
    Dispatcher--> Browser: Code 500 
    Browser--> User: Отображение статуса
    note over User:  Ситуация возможна при использовании консоли, curl и т.д. \nНеобходимо скорректировать параметры
end

alt Вычисление не завершено(или не начато)
    Dispatcher--> Browser: Code 200 \n+ Status={Waiting или In progress}\n+ result="" 
    Browser--> User: Отображение статуса
    note over User: Пробует позже
else #LightGreen Получен результат
  Dispatcher -> LocalCache: Добавление результата для task_id в кэш  
  LocalCache --> Dispatcher: 

  Dispatcher--> Browser: Code 200 \n+ Результат 
  Browser--> User: Отображение результата
   note over User: Конец
end

@enduml